events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location /api/v1/auth/ { proxy_pass http://auth-service:8000/api/v1/auth/; }
        location /api/v1/content/ { proxy_pass http://content-service:8000/api/v1/content/; }
        location /api/v1/media/ { proxy_pass http://media-service:8000/api/v1/media/; }
        location /api/v1/education/ { proxy_pass http://education-service:8000/api/v1/education/; }
        location /api/v1/workspace/ { proxy_pass http://workspace-service:8000/api/v1/workspace/; }
    }
}
